#!/bin/bash

#default old colorscheme
. colorspec
#default for -s
newscheme=('002b36' '073642' '586e75' '657b83' '839496' '93a1a1' 'eee8d5' 'fdf6e3' 'dc322f' 'cb4b16' 'b58900' '859900' '2aa198' '268bd2' '6c71c4' 'd33682')
#default for -t
target="."

function helpText {
            echo "Change the colors in your dotfiles"
            echo "Usage: $0 [-h] [-t target] [-s base00 ... base0f]"
            echo ""
            echo "Default: $0 -t . -s ${newscheme[*]}"
            echo ""
            echo "-h        display this help and exit"
            echo "-t        specify where to apply the changes"
            echo "-s        provide your own base16 colorscheme"
}

while getopts 'hs:t:' OPTION; do
    case "$OPTION" in
        h)
            helpText
            exit 0
            ;;
        s)
            iarg="$OPTARG"
            shift "$((OPTIND -1))"
            newscheme=("$iarg" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}")
            echo "${newscheme[*]}"
            ;;
        t)
            iarg="$OPTARG"
            if [[ -f "$iarg" ]]; then
                echo "Target file provided : $iarg"
                target=$iarg
            elif [[ -d "$iarg" ]]; then
                echo "Target directory provided: $iarg"
                target=$iarg
            else
                echo "Target does not exist: $iarg" >&2
                exit 1
            fi
            ;;
        *)
            helpText
            exit 1
            ;;
    esac
done

if [[ -d "$target" ]]; then
    cd "$target" || exit 1

    for index in "${!oldscheme[*]}"; do
        #grep -r -l "${oldscheme[$index]}" | xargs sed -i "s/${oldscheme[$index]}/${newscheme[$index]}/g"
        echo "$index" > /dev/null
    done
elif [[ -f "$target" ]]; then
    for index in "${!oldscheme[*]}"; do
        sed -i "s/${oldscheme[$index]}/${newscheme[$index]}/g"
    done
fi
