#!/bin/sh
echo "Defining Package Scopes"
QtileDeps="python3-cffi xserver-xorg python3-xcffib python3-cairocffi libpangocairo-1.0-0 xinit python3-pip python3-psutil lm-sensors"
PipPkgs="qtile adblock"
Suite="qutebrowser kitty zsh mpv cmus kitty ranger mupdf groff neovim calcurse keepassxc htop neofetch gdu pulsemixer"
Misc="fonts-mononoki fonts-font-awesome shellcheck flake8 cifs-utils brightnessctl tree wget sl apt-show-versions stow curl xscreensaver newsboat pacvim netcat aspell-en aspell-de debsums"
Pipewire="pipewire pipewire-pulse pipewire-audio-client-libraries"
echo "Creating config directories"
mkdir -p ~/.config/fontconfig ~/.config/kitty ~/.config/qutebrowser ~/.config/qtile ~/.config/nvim ~/.config/htop ~/.config/neofetch
echo "Installing dependencies for qtile"
sudo apt-get install "$QtileDeps"
echo "Installing qtile and adblock"
sudo pip3 install "$PipPkgs"
echo "Installing application suite"
sudo apt-get install "$Suite"
echo "Installing miscellaneous utilities"
sudo apt-get install "$Misc"
echo "Setting up Pipewire"
sudo apt get install "$Pipewire"
touch /etc/pipewire/media-session.d/with-pulseaudio
cp /usr/share/doc/pipewire/examples/systemd/user/pipewire-pulse.* /etc/systemd/user/
touch /etc/pipewire/media-session.d/with-alsa
cp /usr/share/doc/pipewire/examples/alsa.conf.d/99-pipewire-default.conf /etc/alsa/conf.d/
systemctl --user daemon-reload
systemctl --user --now enable pipewire pipewire-pulse
systemctl --user --now enable pipewire pipewire-pulse
# Confirm with LANG=C pactl info | grep '^Server Name'
echo "Setting up XDG compliant zsh"
echo "ZDOTDIR=$HOME/.config/zsh" >> /etc/zsh/zshenv
echo "symlinking dotfiles"
stow -v dots
echo "done"
