on:
  push:
    branches:
      - main

name: 'Checks'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -s sh

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
#       Qtile E401 C0209
#       Qutebrowser C0103 E0602
        pylint -d E401 -d C0209 -d E0602 -d C0103 `find . -name "*.py"|xargs`

#  stylelint:
#    name: Stylelint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: Analysing the css with stylelint
#        uses: actions-hub/stylelint@master
#        env:
#          PATTERN: "./dots/.config/*/*.css"

